### ISSUE TITLE
ModuleNotFoundError: No module named 'extensions.telegram_bot.generators.'

### ISSUE THREAD

**Issue by Orwlit** [innightwolfsleep/text-generation-webui-telegram_bot#104]
I am running this extension on Apple silicon M2 pro, and pip requirements are all installed properly.
However, when I run `python server.py --extensions telegram_bot` under `text-generation-webui/` I got three missing files and one error: 
missing files: 
```
Cant find config_file extensions/telegram_bot/telegram_config.cfg
Cant find generator_params_file
Cant find user_rules_file_path: configs/telegram_user_rules.json
```
error: 
```
ModuleNotFoundError: No module named 'extensions.telegram_bot.generators.'
```
full logging
```
(textgen) ➜  text-generation-webui git:(main) ✗ python server.py --extensions telegram_bot
/Users/cr_mac_001/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
'NoneType' object has no attribute 'cadam32bit_grad_fp32'
2023-08-02 00:59:29 INFO:Loading the extension "telegram_bot"...
Cant find config_file extensions/telegram_bot/telegram_config.cfg
Cant find generator_params_file
Cant find user_rules_file_path: configs/telegram_user_rules.json
Telegram bot generator script:  
Exception in thread Thread-1 (run_server):
Traceback (most recent call last):
  File "/Users/cr_mac_001/userCode/text-generation-webui/extensions/telegram_bot/TelegramBotGenerator.py", line 26, in init
    importlib.import_module("generators." + script), "Generator")
  File "/Users/cr_mac_001/miniconda3/envs/textgen/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'generators'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cr_mac_001/miniconda3/envs/textgen/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Users/cr_mac_001/miniconda3/envs/textgen/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/cr_mac_001/userCode/text-generation-webui/extensions/telegram_bot/script.py", line 8, in run_server
    tg_server = TelegramBotWrapper(
  File "/Users/cr_mac_001/userCode/text-generation-webui/extensions/telegram_bot/TelegramBotWrapper.py", line 195, in __init__
    Generator.init(self.generator_script, self.model_path)
  File "/Users/cr_mac_001/userCode/text-generation-webui/extensions/telegram_bot/TelegramBotGenerator.py", line 29, in init
    importlib.import_module("extensions.telegram_bot.generators." + script), "Generator")
  File "/Users/cr_mac_001/miniconda3/envs/textgen/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'extensions.telegram_bot.generators.'
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
```
the whole structure of directory `telegram_bot` looks like this, and there is no `telegram_bot/telegram_config.cfg` at all.
```
(textgen) ➜  text-generation-webui git:(main) ✗ cd extensions/telegram_bot 
(textgen) ➜  telegram_bot git:(main) ✗ tree
.
├── LICENSE
├── TelegramBotGenerator.py
├── TelegramBotSdApi.py
├── TelegramBotSilero.py
├── TelegramBotUser.py
├── TelegramBotWrapper.py
├── __pycache__
│   ├── TelegramBotGenerator.cpython-310.pyc
│   ├── TelegramBotSdApi.cpython-310.pyc
│   ├── TelegramBotSilero.cpython-310.pyc
│   ├── TelegramBotUser.cpython-310.pyc
│   ├── TelegramBotWrapper.cpython-310.pyc
│   └── script.cpython-310.pyc
├── configs
│   ├── telegram_admins.txt
│   ├── telegram_config.json
│   ├── telegram_generator_params.json
│   ├── telegram_sd_config.json
│   ├── telegram_token.txt
│   ├── telegram_user_rules.json
│   └── telegram_users.txt
├── generators
│   ├── GeneratorLangchainLlamaCpp.py
│   ├── GeneratorLlamaCpp.py
│   ├── GeneratorTextGeneratorWebui.py
│   ├── GeneratorTextGeneratorWebuiApi.py
│   └── GeneratorTransformers.py
├── history
│   └── telegram_history_here.txt
├── manuals
│   ├── readme.md
│   ├── telegram_bot_conversation.PNG
│   ├── telegram_bot_load.PNG
│   ├── telegram_bot_message.PNG
│   ├── telegram_bot_message_narrow.png
│   ├── telegram_bot_prefixes.PNG
│   ├── telegram_bot_save.PNG
│   ├── telegram_bot_start_option.PNG
│   ├── telegram_bot_start_option_narrow.PNG
│   ├── telegram_bot_translate.PNG
│   └── telegram_bot_voice.PNG
├── readme.md
├── requirements.txt
└── script.py

6 directories, 39 files

```
Maybe after some update, `telegram_config.cfg` was deleted from this repo accidentally and caused this error???

**Comment by innightwolfsleep** [comment]
You right!
My miss. Changed config files to .json but forgot to change path.

Try if it okay now

**Comment by Orwlit** [comment]
I see that .cfg file, Thanks!!!
but the problem is not fixed completely with these files couldn't found:
```
...
Cant find generator_params_file
Cant find user_rules_file_path: extensions\telegram_bot\configs\telegram_user_rules.json
Telegram bot generator script:  GeneratorTextGeneratorWebui
...
```
However I noticed that each dirs are connected by `\`, so I assume you are developing this extension on Windows.
After I replaced all `\\` into `/` in `telegram_config.cfg`, the problem solved LOL. It look like this:
```
{
	"bot_mode": "admin",
	"generator_script": "GeneratorTextGeneratorWebui",
	"model_path": "not used for text-generator-webui",
	"characters_dir_path": "characters",
	"default_char": "Example.yaml",
	"presets_dir_path": "presets",
	"default_preset": "Shortwave.yaml",
	"model_lang": "en",
	"user_lang": "en",
	"history_dir_path": "extensions/telegram_bot/history",
	"token_file_path": "extensions/telegram_bot/configs/telegram_token.txt",
	"admins_file_path": "extensions/telegram_bot/configs/telegram_admins.txt",
	"users_file_path": "extensions/telegram_bot/configs/users_file_path.txt",
	"generator_params_file_path": "extensions/telegram_bot/configs/telegram_generator_params.json",
	"user_rules_file_path": "extensions/telegram_bot/configs/telegram_user_rules.json",
	"telegram_sd_config": "extensions/telegram_bot/configs/telegram_sd_config.json",
	"stopping_strings": ["<END>", "<START>", "end{code}"],
	"eos_token": "None",
	"translation_as_hidden_text": "on"
}
```
But then I encounter a connection error to telegram. I guess it is because I'm in China with Internet connecting issue...
Thanks again! It would be great if you add macOS or Linux support with `/` of this file

this is the whole log of telegram connecting issue:
```
(textgen) ➜  text-generation-webui git:(main) ✗ python server.py --extensions telegram_bot
/Users/cr_mac_001/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
'NoneType' object has no attribute 'cadam32bit_grad_fp32'
2023-08-02 02:14:47 INFO:Loading the extension "telegram_bot"...
Telegram bot generator script:  GeneratorTextGeneratorWebui
2023-08-02 02:14:47 WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x29e4d5f30>: Failed to establish a new connection: [Errno 61] Connection refused')': /botXXXXXXX/getMe
2023-08-02 02:14:47 WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x29f512200>: Failed to establish a new connection: [Errno 61] Connection refused')': /botXXXXXXX/getMe
2023-08-02 02:14:47 WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x29f512fe0>: Failed to establish a new connection: [Errno 61] Connection refused')': /botXXXXXXX/getMe
Exception in thread Thread-1 (run_server):
Traceback (most recent call last):
  File "/Users/cr_mac_001/miniconda3/envs/textgen/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/connection.py", line 140, in _new_conn
    conn = connection.create_connection(
  File "/Users/cr_mac_001/miniconda3/envs/textgen/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/Users/cr_mac_001/miniconda3/envs/textgen/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cr_mac_001/miniconda3/envs/textgen/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 614, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/Users/cr_mac_001/miniconda3/envs/textgen/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 360, in _make_request
    self._validate_conn(conn)
  File "/Users/cr_mac_001/miniconda3/envs/textgen/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 857, in _validate_conn
    super(HTTPSConnectionPool, self)._validate_conn(conn)
  File "/Users/cr_mac_001/miniconda3/envs/textgen/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 289, in _validate_conn
    conn.connect()
  File "/Users/cr_mac_001/miniconda3/envs/textgen/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/connection.py", line 284, in connect
    conn = self._new_conn()
  File "/Users/cr_mac_001/miniconda3/envs/textgen/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/connection.py", line 149, in _new_conn
    raise NewConnectionError(
telegram.vendor.ptb_urllib3.urllib3.exceptions.NewConnectionError: <telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x29f54d0f0>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cr_mac_001/miniconda3/envs/textgen/lib/python3.10/site-packages/telegram/utils/request.py", line 259, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "/Users/cr_mac_001/miniconda3/envs/textgen/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 68, in request
    return self.request_encode_body(method, url, fields=fields,
  File "/Users/cr_mac_001/miniconda3/envs/textgen/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/Users/cr_mac_001/miniconda3/envs/textgen/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/Users/cr_mac_001/miniconda3/envs/textgen/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 691, in urlopen
    return self.urlopen(method, url, body, headers, retries,
  File "/Users/cr_mac_001/miniconda3/envs/textgen/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 691, in urlopen
    return self.urlopen(method, url, body, headers, retries,
  File "/Users/cr_mac_001/miniconda3/envs/textgen/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 691, in urlopen
    return self.urlopen(method, url, body, headers, retries,
  File "/Users/cr_mac_001/miniconda3/envs/textgen/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 665, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "/Users/cr_mac_001/miniconda3/envs/textgen/lib/python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/retry.py", line 376, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
telegram.vendor.ptb_urllib3.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /botXXXXXXX/getMe (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x29f54d0f0>: Failed to establish a new connection: [Errno 61] Connection refused'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/cr_mac_001/miniconda3/envs/textgen/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Users/cr_mac_001/miniconda3/envs/textgen/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/cr_mac_001/userCode/text-generation-webui/extensions/telegram_bot/script.py", line 11, in run_server
    tg_server.run_telegram_bot()
  File "/Users/cr_mac_001/userCode/text-generation-webui/extensions/telegram_bot/TelegramBotWrapper.py", line 249, in run_telegram_bot
    self.updater.start_polling()
  File "/Users/cr_mac_001/miniconda3/envs/textgen/lib/python3.10/site-packages/telegram/ext/updater.py", line 422, in start_polling
    self._init_thread(self.dispatcher.start, "dispatcher", ready=dispatcher_ready)
  File "/Users/cr_mac_001/miniconda3/envs/textgen/lib/python3.10/site-packages/telegram/ext/updater.py", line 342, in _init_thread
    name=f"Bot:{self.bot.id}:{name}",
  File "/Users/cr_mac_001/miniconda3/envs/textgen/lib/python3.10/site-packages/telegram/bot.py", line 377, in id
    return self.bot.id
  File "/Users/cr_mac_001/miniconda3/envs/textgen/lib/python3.10/site-packages/telegram/bot.py", line 371, in bot
    self._bot = self.get_me()
  File "/Users/cr_mac_001/miniconda3/envs/textgen/lib/python3.10/site-packages/telegram/bot.py", line 134, in decorator
    result = func(*args, **kwargs)
  File "/Users/cr_mac_001/miniconda3/envs/textgen/lib/python3.10/site-packages/telegram/bot.py", line 458, in get_me
    result = self._post('getMe', timeout=timeout, api_kwargs=api_kwargs)
  File "/Users/cr_mac_001/miniconda3/envs/textgen/lib/python3.10/site-packages/telegram/bot.py", line 299, in _post
    return self.request.post(
  File "/Users/cr_mac_001/miniconda3/envs/textgen/lib/python3.10/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/Users/cr_mac_001/miniconda3/envs/textgen/lib/python3.10/site-packages/telegram/utils/request.py", line 265, in _request_wrapper
    raise NetworkError(f'urllib3 HTTPError {error}') from error
telegram.error.NetworkError: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /botXXXXXXX/getMe (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x29f54d0f0>: Failed to establish a new connection: [Errno 61] Connection refused'))
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
```

**Comment by innightwolfsleep** [comment]
> After I replaced all \\ into / in telegram_config.cfg, the problem solved LOL. It look like this:

Yes, that's true. I think I have to add some os.path methods to solve this problem in future.

> telegram.vendor.ptb_urllib3.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /botXXXXXXX/getMe (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x29f54d0f0>: Failed to establish a new connection: [Errno 61] Connection refused'))

I can't help you here. Vpn or shadowsocks... but I am not expert how to path through firewall.
