### ISSUE TITLE
KeyError: 'guidance_scale'

### ISSUE THREAD

**Issue by krypterro** [innightwolfsleep/text-generation-webui-telegram_bot#107]
Just updated Oobabooga, now I'm getting blank replies and this error in console when using the telegram_bot extension. No error using the UI or API otherwise.

```
:Traceback (most recent call last):
  File "/home/zino/oobabooga/text-generation-webui/modules/text_generation.py", line 344, in generate_reply_custom
    for reply in shared.model.generate_with_streaming(question, state):
  File "/home/zino/oobabooga/text-generation-webui/modules/exllama.py", line 85, in generate_with_streaming
    if state['guidance_scale'] == 1:
KeyError: 'guidance_scale'
```

**Comment by innightwolfsleep** [comment]
Made fast fix. #108
Please check, can't check on my own now.

**Comment by TacticalBacon00** [comment]
I get the following error when loading the extension with the updated telegram_generator_params.json
```python
2023-08-07 19:26:28 INFO:Loading the extension "telegram_bot"...
Exception in thread Thread-7 (run_server):
Traceback (most recent call last):
  File "B:\AI\LLM\oobabooga_windows\installer_files\env\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "B:\AI\LLM\oobabooga_windows\installer_files\env\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "B:\AI\LLM\oobabooga_windows\text-generation-webui\extensions\telegram_bot\script.py", line 8, in run_server
    tg_server = TelegramBotWrapper(
  File "B:\AI\LLM\oobabooga_windows\text-generation-webui\extensions\telegram_bot\TelegramBotWrapper.py", line 177, in __init__
    self.generation_params = json.loads(params_file.read())
  File "B:\AI\LLM\oobabooga_windows\installer_files\env\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "B:\AI\LLM\oobabooga_windows\installer_files\env\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "B:\AI\LLM\oobabooga_windows\installer_files\env\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 27 column 1 (char 669)
```

When I remove the final comma on line 26 (last character on the "negative_prompt" key line), it looks like the bot starts without errors now:
```json
{
    "max_new_tokens": 256,
    "seed": -1.0,
    "temperature": 0.7,
    "top_p": 0.1,
    "top_k": 40,
    "typical_p": 1,
    "repetition_penalty": 1.18,
    "encoder_repetition_penalty": 1,
    "no_repeat_ngram_size": 0,
    "min_length": 0,
    "do_sample": true,
    "penalty_alpha": 0,
    "num_beams": 1,
    "length_penalty": 1,
    "early_stopping": false,
    "add_bos_token": true,
    "ban_eos_token": false,
    "truncation_length": 1024,
    "custom_stopping_strings": "",
    "chat_prompt_size": 1024,
    "chat_generation_attempts": 1,
    "stop_at_newline": false,
    "skip_special_tokens": true,
    "guidance_scale": 1,
    "negative_prompt": ""
}
```

**Comment by krypterro** [comment]
The error is gone now with the above fixes, but I'm getting looping blank replies, but that could be my config that I was having problems with to begin with.
