### ISSUE TITLE
Read me needs an update, Also need help cant find module named acclerate. 

### ISSUE THREAD

**Issue by Maki9009** [innightwolfsleep/text-generation-webui-telegram_bot#126]
cant find the telegram token.txt file, and i also not sure where I'm supposed to put the --extensions telegram_bot

**Comment by Maki9009** [comment]
Nvm found the server.py file.. but anyway to make it just run everytime i use the start_windows.bat? 

i still don't know where the telegram token.txt is by the way

**Comment by Maki9009** [comment]
So i found the telegramtoken.txt but the readme needs an update to explain where to find it, and also when i ran the python servery.py --extension telegram_bot i got this error 

E:\oobabooga_windows\text-generation-webui>python server.py --extension telegram_bot
Traceback (most recent call last):
  File "E:\oobabooga_windows\text-generation-webui\server.py", line 28, in <module>
    from modules import (
  File "E:\oobabooga_windows\text-generation-webui\modules\chat.py", line 17, in <module>
    from modules.text_generation import (
  File "E:\oobabooga_windows\text-generation-webui\modules\text_generation.py", line 23, in <module>
    from modules.models import clear_torch_cache, local_rank
  File "E:\oobabooga_windows\text-generation-webui\modules\models.py", line 10, in <module>
    from accelerate import infer_auto_device_map, init_empty_weights
ModuleNotFoundError: No module named 'accelerate'
