### ISSUE TITLE
Getting an TraceBack error everytime i text from telegram

### ISSUE THREAD

**Issue by Maki9009** [innightwolfsleep/text-generation-webui-telegram_bot#129]
whatever i text on telegram i get this error, and the telegram bot says its typing and then just stops and doesn't send anything
This is the traceback error 

user_text What’s up
user_text What’s up
generate_answer local variable 'tokens' referenced before assignment
cannot unpack non-iterable NoneType object
Exception in thread Thread-14 (thread_get_message):
Traceback (most recent call last):
  File "E:\oobabooga_windows\installer_files\env\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "E:\oobabooga_windows\installer_files\env\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "E:\oobabooga_windows\text-generation-webui\extensions\telegram_bot\TelegramBotWrapper.py", line 765, in thread_get_message
    raise e
  File "E:\oobabooga_windows\text-generation-webui\extensions\telegram_bot\TelegramBotWrapper.py", line 746, in thread_get_message
    answer, system_message = self.generate_answer(
TypeError: cannot unpack non-iterable NoneType object

**Comment by innightwolfsleep** [comment]
Add some new parameters to config #130. At my config (llama.cpp + llama-2-7b) works fine. 

Also, you can try to use api mode:
 - add --api to oobaboga flags
 - in telegram_config.json set "generator_script": "GeneratorTextGeneratorWebuiApi".
 
 Please, share if it helps or not.

**Comment by Maki9009** [comment]
im not sure what i did wrong when i tried here.. but idk after restarting the webui it started to work

**Comment by svenstaro** [comment]
Can't this be closed, then?
