### ISSUE TITLE
KeyError: 'grammar_string'

### ISSUE THREAD

**Issue by svenstaro** [innightwolfsleep/text-generation-webui-telegram_bot#153]
Hey, I think this project is a really cool idea.

Sadly, I can't currently get it to work. I'm using the extension mode. Whenever I try to chat with my bot, I get a stacktrace:
```
Traceback (most recent call last):
  File "/app/modules/callbacks.py", line 56, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "/app/modules/llamacpp_model.py", line 132, in generate
    self.load_grammar(state['grammar_string'])
KeyError: 'grammar_string'
Output generated in 0.28 seconds (0.00 tokens/s, 0 tokens, context 77, seed 2030786626)
```
I'm using text-generation-webui version `0197fdddf106270ccf77fc2757d7bc53cc9729d4` and text-generation-webui-telegram_bot version `7c47ae9ca46120466a65316ae1dcad198c1eded7`.

This is my ext_config.json:
```
    1 {
    2     "bot_mode": "admin",
    3     "user_name_template": "",
    4     "generator_script": "generator_text_generator_webui",
    5     "model_path": "unused",
    6     "characters_dir_path": "characters",
    7     "default_char": "Example.yaml",
    8     "presets_dir_path": "presets",
    9     "default_preset": "simple-1.txt",
   10     "model_lang": "en",
   11     "user_lang": "en",
   12     "history_dir_path": "extensions/telegram_bot/history",
   13     "token_file_path": "extensions/telegram_bot/configs/telegram_token.txt",
   14     "admins_file_path": "extensions/telegram_bot/configs/telegram_admins.txt",
   15     "users_file_path": "extensions/telegram_bot/configs/telegram_users.txt",
   16     "generator_params_file_path": "extensions/telegram_bot/configs/generator_params.json",
   17     "user_rules_file_path": "extensions/telegram_bot/configs/telegram_user_rules.json",
   18     "sd_config_file_path": "extensions/telegram_bot/configs/sd_config.json",
   19     "translation_as_hidden_text": "on",
   20     "sd_api_url": "http:/127.0.0.1:7860",
   21     "proxy_url": ""
   22 }
```
Interestingly enough, getting a picture via the SD API works using the bot.

I wonder whether maybe my versions of the webui I too recent?

**Comment by innightwolfsleep** [comment]
Seems this is new parameter in oobabooga.

Added #154, but I can't test it right now. 

Please, share a feedback - if it helps or not.

**Comment by svenstaro** [comment]
Yup, that works! Great work, thanks.
