### ISSUE TITLE
Pydantic dep crashing ui

### ISSUE THREAD

**Issue by leros1337** [innightwolfsleep/text-generation-webui-telegram_bot#161]
Pydantic==1.9.0 in deps (installing for ui extension) breaking ui start.

`Traceback (most recent call last):
  File "E:\ai-llm\text-generation-webui\server.py", line 14, in <module>
    import gradio as gr
  File "E:\ai-llm\text-generation-webui\installer_files\env\Lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "E:\ai-llm\text-generation-webui\installer_files\env\Lib\site-packages\gradio\components\__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "E:\ai-llm\text-generation-webui\installer_files\env\Lib\site-packages\gradio\components\annotated_image.py", line 14, in <module>
    from gradio.components.base import IOComponent, _Keywords
  File "E:\ai-llm\text-generation-webui\installer_files\env\Lib\site-packages\gradio\components\base.py", line 20, in <module>
    from fastapi import UploadFile
  File "E:\ai-llm\text-generation-webui\installer_files\env\Lib\site-packages\fastapi\__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "E:\ai-llm\text-generation-webui\installer_files\env\Lib\site-packages\fastapi\applications.py", line 16, in <module>
    from fastapi import routing
  File "E:\ai-llm\text-generation-webui\installer_files\env\Lib\site-packages\fastapi\routing.py", line 22, in <module>
    from fastapi import params
  File "E:\ai-llm\text-generation-webui\installer_files\env\Lib\site-packages\fastapi\params.py", line 5, in <module>
    from fastapi.openapi.models import Example
  File "E:\ai-llm\text-generation-webui\installer_files\env\Lib\site-packages\fastapi\openapi\models.py", line 170, in <module>
    class Schema(BaseModel):
  File "E:\ai-llm\text-generation-webui\installer_files\env\Lib\site-packages\pydantic\main.py", line 291, in new
    cls.signature = ClassAttribute('signature', generate_model_signature(cls.init, fields, config))
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ai-llm\text-generation-webui\installer_files\env\Lib\site-packages\pydantic\utils.py", line 256, in generate_model_signature
    merged_params[param_name] = Parameter(
                                ^^^^^^^^^^
  File "E:\ai-llm\text-generation-webui\installer_files\env\Lib\inspect.py", line 2725, in init
    raise ValueError('{!r} is not a valid parameter name'.format(name))
ValueError: 'not' is not a valid parameter name
Press any key to continue . . .`

Issue on github: https://github.com/tiangolo/fastapi/issues/5048#issuecomment-1229183881
Start fine version: `1.10.13`

**Comment by innightwolfsleep** [comment]
Thanks for fixing it!
