### ISSUE TITLE
telegram.error.NetworkError: urllib3 HTTPError

### ISSUE THREAD

**Issue by tanfarou** [innightwolfsleep/text-generation-webui-telegram_bot#23]
Hi,
I get this error, it seems like it is related to SSL but can't be sure. It works with Telegram app intermittently after I send a few messages.
-----
Loaded the model in 4.64 seconds.
Loading the extension "telegram_bot"... Ok.
Loading the extension "gallery"... Ok.
Telegram bot started! <telegram.ext.updater.Updater object at 0x00000243C01C3060>
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Exception in thread Thread-8 (tr_get_message):
Traceback (most recent call last):
  File "D:\Git_Projects\oobabooga_windows\installer_files\env\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 614, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "D:\Git_Projects\oobabooga_windows\installer_files\env\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 360, in _make_request
    self._validate_conn(conn)
  File "D:\Git_Projects\oobabooga_windows\installer_files\env\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 857, in _validate_conn
    super(HTTPSConnectionPool, self)._validate_conn(conn)
  File "D:\Git_Projects\oobabooga_windows\installer_files\env\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 289, in _validate_conn
    conn.connect()
  File "D:\Git_Projects\oobabooga_windows\installer_files\env\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connection.py", line 319, in connect
    self.sock = ssl_wrap_socket(
  File "D:\Git_Projects\oobabooga_windows\installer_files\env\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\util\ssl_.py", line 324, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "D:\Git_Projects\oobabooga_windows\installer_files\env\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\Git_Projects\oobabooga_windows\installer_files\env\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "D:\Git_Projects\oobabooga_windows\installer_files\env\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Git_Projects\oobabooga_windows\installer_files\env\lib\site-packages\telegram\utils\request.py", line 259, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "D:\Git_Projects\oobabooga_windows\installer_files\env\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\request.py", line 68, in request
    return self.request_encode_body(method, url, fields=fields,
  File "D:\Git_Projects\oobabooga_windows\installer_files\env\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "D:\Git_Projects\oobabooga_windows\installer_files\env\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "D:\Git_Projects\oobabooga_windows\installer_files\env\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 665, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "D:\Git_Projects\oobabooga_windows\installer_files\env\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\util\retry.py", line 347, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "D:\Git_Projects\oobabooga_windows\installer_files\env\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "D:\Git_Projects\oobabooga_windows\installer_files\env\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 614, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "D:\Git_Projects\oobabooga_windows\installer_files\env\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 360, in _make_request
    self._validate_conn(conn)
  File "D:\Git_Projects\oobabooga_windows\installer_files\env\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 857, in _validate_conn
    super(HTTPSConnectionPool, self)._validate_conn(conn)
  File "D:\Git_Projects\oobabooga_windows\installer_files\env\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 289, in _validate_conn
    conn.connect()
  File "D:\Git_Projects\oobabooga_windows\installer_files\env\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connection.py", line 319, in connect
    self.sock = ssl_wrap_socket(
  File "D:\Git_Projects\oobabooga_windows\installer_files\env\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\util\ssl_.py", line 324, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "D:\Git_Projects\oobabooga_windows\installer_files\env\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\Git_Projects\oobabooga_windows\installer_files\env\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "D:\Git_Projects\oobabooga_windows\installer_files\env\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
telegram.vendor.ptb_urllib3.urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Git_Projects\oobabooga_windows\installer_files\env\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "D:\Git_Projects\oobabooga_windows\installer_files\env\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Git_Projects\oobabooga_windows\text-generation-webui\extensions\telegram_bot\TelegramBotWrapper.py", line 387, in tr_get_message
    message = context.bot.send_message(
  File "D:\Git_Projects\oobabooga_windows\installer_files\env\lib\site-packages\telegram\bot.py", line 134, in decorator
    result = func(*args, **kwargs)
  File "D:\Git_Projects\oobabooga_windows\installer_files\env\lib\site-packages\telegram\bot.py", line 534, in send_message
    return self._message(  # type: ignore[return-value]
  File "D:\Git_Projects\oobabooga_windows\installer_files\env\lib\site-packages\telegram\ext\extbot.py", line 203, in _message
    result = super()._message(
  File "D:\Git_Projects\oobabooga_windows\installer_files\env\lib\site-packages\telegram\bot.py", line 344, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "D:\Git_Projects\oobabooga_windows\installer_files\env\lib\site-packages\telegram\bot.py", line 299, in _post
    return self.request.post(
  File "D:\Git_Projects\oobabooga_windows\installer_files\env\lib\site-packages\telegram\utils\request.py", line 361, in post
    result = self._request_wrapper(
  File "D:\Git_Projects\oobabooga_windows\installer_files\env\lib\site-packages\telegram\utils\request.py", line 265, in _request_wrapper
    raise NetworkError(f'urllib3 HTTPError {error}') from error
telegram.error.NetworkError: urllib3 HTTPError ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
----------------

**Comment by innightwolfsleep** [comment]
added no_sleep_callback to avoid connection timeout
