### ISSUE TITLE
Repeating "You" after a few messages

### ISSUE THREAD

**Issue by tanfarou** [innightwolfsleep/text-generation-webui-telegram_bot#33]
Hi,

After exchanging 2-3 messages, I get a list of repeating empty "You" in the same response from the bot. Also the log show the below but only in one of instance, so it could be unrelated:

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\Git_Projects\oobabooga_windows\installer_files\env\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 429, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\Git_Projects\oobabooga_windows\installer_files\env\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "D:\Git_Projects\oobabooga_windows\installer_files\env\lib\site-packages\fastapi\applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "D:\Git_Projects\oobabooga_windows\installer_files\env\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\Git_Projects\oobabooga_windows\installer_files\env\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "D:\Git_Projects\oobabooga_windows\installer_files\env\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "D:\Git_Projects\oobabooga_windows\installer_files\env\lib\site-packages\starlette\middleware\cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "D:\Git_Projects\oobabooga_windows\installer_files\env\lib\site-packages\starlette\middleware\cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "D:\Git_Projects\oobabooga_windows\installer_files\env\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "D:\Git_Projects\oobabooga_windows\installer_files\env\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "D:\Git_Projects\oobabooga_windows\installer_files\env\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "D:\Git_Projects\oobabooga_windows\installer_files\env\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "D:\Git_Projects\oobabooga_windows\installer_files\env\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "D:\Git_Projects\oobabooga_windows\installer_files\env\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "D:\Git_Projects\oobabooga_windows\installer_files\env\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "D:\Git_Projects\oobabooga_windows\installer_files\env\lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "D:\Git_Projects\oobabooga_windows\installer_files\env\lib\site-packages\fastapi\routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "D:\Git_Projects\oobabooga_windows\installer_files\env\lib\site-packages\gradio\routes.py", line 461, in predict
    if app.get_blocks().dependencies[fn_index_inferred]["cancels"]:
IndexError: list index out of range

**Comment by innightwolfsleep** [comment]
I am not sure if it realy problem of telegram bot. Perhaps it is problem of model or prompting? Errors not linked to bot, a i can see. May by you had to open discussionin in oobabooga webui repo?

p.s. I had the same "repeating" with pure oobabooga webui, usualy it was problem of my bad prompting or settings.

**Comment by tanfarou** [comment]
Yes, the above error in the log seems to be unrelated. However, I think I could not explain the error within Telegram earlier; here's the screenshot.

The below is a part of the bot response. The character is called Ava and You is actually the user which in this case is me. This appears after the Character's response, the list of repetitions with just "You" keeps growing.  I don't see the same error with the text web ui. I'll try to figure it out but if you have any further ideas, let me know. Thanks.


<img width="623" alt="Screenshot 2023-05-18 014806" src="https://github.com/innightwolfsleep/text-generation-webui-telegram_bot/assets/111169072/e804f2c9-5d61-45f1-9522-68411433b0b5">

**Comment by innightwolfsleep** [comment]
Perhaps it is result of differennt eos_token/stopping_strings in telegram_bot and webui. Webui is more complicated. 

In telegram_bot, by default, used only stopping_strings and empty eos_token. If you set eos_token=['\n'] - repeating should be truncated, but telegram_bot wont send multilines message.

**Comment by tanfarou** [comment]
Thanks for the info. Good news is that I updated Oobabooga, and the problem seems to have been fixed. Thanks for looking into it. I'll close this ticket.
