### ISSUE TITLE
Unable to load characters or models

### ISSUE THREAD

**Issue by Michael7575** [innightwolfsleep/text-generation-webui-telegram_bot#82]
I am unable to load new characters or models with `/load` and `/models` command in Telegram. The bot simply responds to the command and I believe it is using the `Example.yaml` character.

**Comment by innightwolfsleep** [comment]
Currently, only **/start** command allowed,
All another actions allowed with buttons. 

p.s. find a bug with .yaml characters. Will fix it today.

**Comment by innightwolfsleep** [comment]
Yeah, there was a bug - history file format changed a bunch commit ago, so there was a bug prevent a loading or reseting characters who was saved in history before. Should be fixed now.

**Comment by innightwolfsleep** [comment]
readme.md fixed too. My bad.

**Comment by Michael7575** [comment]
I just started to getting the following error with the latest PR. 

```
Llama.generate: prefix-match hit
Output generated in 2.62 seconds (4.97 tokens/s, 13 tokens, context 618, seed 1920189083)
generate_answer 'character_menu'
cannot unpack non-iterable NoneType object
Exception in thread Thread-37 (thread_get_message):
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/michael/Desktop/oobabooga_macos/text-generation-webui/extensions/telegram_bot/TelegramBotWrapper.py", line 496, in thread_get_message
    raise e
  File "/Users/michael/Desktop/oobabooga_macos/text-generation-webui/extensions/telegram_bot/TelegramBotWrapper.py", line 483, in thread_get_message
    answer, system_message = self.generate_answer(user_in=user_text, chat_id=chat_id)
    ^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object
```

**Comment by innightwolfsleep** [comment]
Just reinstalled text-generation-webui and telegram extension from last commit and checked. Thats work fine.
![image](https://github.com/innightwolfsleep/text-generation-webui-telegram_bot/assets/20921671/e7d9667f-2b65-4efb-a60b-3355a5de30e6)
Error looks like we have a problem with answer from text-generation-webui - thats happend whesomething changed in text-generation-webui\modules\text_generation.py. But I cant repeat this bug my own.

**Comment by Michael7575** [comment]
I reinstall webui and extension and it works now. Thanks!
